#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
#if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
#    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
#fi
### BEGIN INIT INFO
# Provides:          FDLS
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Field Day logging server
# Description:       Logging server compatible with HamLog clients
### END INIT INFO

# Author: Detrick Merz <k4iz@arrl.net>
#

DESC="Field Day logging server"
DAEMON=/home/pi/Field-Day-LS/FDLS.pl
PIDFILE=/var/run/FDLS.pid
NAME=FDLS

test -f $DAEMON || exit 0

set -e

case "$1" in
	start)
		echo -n "Starting $DESC: "
		start-stop-daemon --start --pidfile $PIDFILE --startas $DAEMON -- >> /var/log/FDLS.log
		echo "$NAME."
		;;
	stop)
		echo -n "Stopping $DESC: "
		# --quiet
		start-stop-daemon --stop --signal 15 --pidfile $PIDFILE --startas $DAEMON --remove-pidfile
		echo "$NAME."
		;;
esac
